---@class vim.lsp.Config
return {
	cmd = { "ruff", "server" },
	cmd_env = { RUFF_TRACE = "messages" },
	init_options = {
		settings = {
			logLevel = "error",
			format = { preview = true },
			lint = {
				enable = true,
				preview = true,
				select = { "E", "F", "N" },
				extendSelect = {
					"W",
					"I",
					"UP007",
					"UP015",
					"FAST001",
					"FAST002",
					"FAST003",
					"RUF100",
					"RUF101",
				},
				ignore = {},
				extendIgnore = {},
			},
			codeAction = {
				disableRuleComment = { enable = true },
				fixViolation = { enable = true },
			},
			showSyntaxErrors = true,
			organizeImports = true,
			fixAll = true,
			lineLength = 120,
			exclude = {
				".git",
				".ipynb_checkpoints",
				".mypy_cache",
				".pyenv",
				".pytest_cache",
				".pytype",
				".ruff_cache",
				".venv",
				".vscode",
				"__pypackages__",
				"_build",
				"build",
				"dist",
				"site-packages",
				"venv",
			},
		},
	},
	filetypes = { "python" },
	root_markers = { "pyproject.toml", "ruff.toml", ".ruff.toml" },
}
